name: 'Magento 2 - Build and Publish'

on:
  push:
    branches: ['**']
    paths: ['.github/workflows/magento2.yml', 'magento2/**']

jobs:
  elasticsearch:
    name: 'Elasticsearch'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/magento2-elasticsearch
          path: magento2/elasticsearch/
          always_pull: true
          tags: latest
          push: ${{ github.ref == 'refs/heads/master' }}

  mysql:
    name: 'MySQL'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/magento2-mysql
          path: magento2/mysql/
          always_pull: true
          tags: latest
          push: ${{ github.ref == 'refs/heads/master' }}

  nginx:
    name: 'Nginx'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/magento2-nginx
          path: magento2/nginx/
          always_pull: true
          tags: latest
          push: ${{ github.ref == 'refs/heads/master' }}

  php:
    name: 'PHP'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/magento2-php
          path: magento2/php/
          always_pull: true
          tags: latest
          push: ${{ github.ref == 'refs/heads/master' }}
