name: "PHP images"

on:
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/php.yml"
      - "common/blackfire-entrypoint/**"
      - "drupal/php/**"
      - "magento2/php/**"
      - "sylius/php/**"
      - "symfony/php/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:

env:
  # Latest version of the Blackfire PHP probe
  BLACKFIRE_PROBE_VERSION: "1.46.4"

jobs:
  blackfire_entrypoint:
    name: "Blackfire Entrypoint"
    runs-on: ubuntu-latest

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./common/blackfire-entrypoint/
          file: ./common/blackfire-entrypoint/Dockerfile
          tags: ajardin/blackfire-entrypoint:latest
          push: ${{ github.ref == 'refs/heads/master' }}

  php_magento_72:
    name: "Magento - 7.2"
    runs-on: ubuntu-latest
    needs: blackfire_entrypoint

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./magento2/php/7.2/
          file: ./magento2/php/7.2/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/magento2-php:7.2
          push: ${{ github.ref == 'refs/heads/master' }}

  php_magento_73:
    name: "Magento - 7.3"
    runs-on: ubuntu-latest
    needs: blackfire_entrypoint

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./magento2/php/7.3/
          file: ./magento2/php/7.3/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/magento2-php:7.3
          push: ${{ github.ref == 'refs/heads/master' }}

  php_magento_74:
    name: "Magento - 7.4"
    runs-on: ubuntu-latest
    needs: blackfire_entrypoint

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./magento2/php/7.4/
          file: ./magento2/php/7.4/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: |
            ajardin/magento2-php:7.4
            ajardin/magento2-php:latest
          push: ${{ github.ref == 'refs/heads/master' }}

  php_symfony_72:
    name: "Symfony - 7.2"
    runs-on: ubuntu-latest
    needs: blackfire_entrypoint

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./symfony/php/7.2/
          file: ./symfony/php/7.2/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/symfony-php:7.2
          push: ${{ github.ref == 'refs/heads/master' }}

  php_symfony_73:
    name: "Symfony - 7.3"
    runs-on: ubuntu-latest
    needs: blackfire_entrypoint

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./symfony/php/7.3/
          file: ./symfony/php/7.3/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/symfony-php:7.3
          push: ${{ github.ref == 'refs/heads/master' }}

  php_symfony_74:
    name: "Symfony - 7.4"
    runs-on: ubuntu-latest
    needs: blackfire_entrypoint

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image (7.4 for Symfony)"
        uses: docker/build-push-action@v2
        with:
          context: ./symfony/php/7.4/
          file: ./symfony/php/7.4/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: |
            ajardin/symfony-php:7.4
            ajardin/symfony-php:latest
          push: ${{ github.ref == 'refs/heads/master' }}

  php_symfony_80:
    name: "Symfony - 8.0"
    runs-on: ubuntu-latest
    needs: blackfire_entrypoint

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image (8.0 for Symfony)"
        uses: docker/build-push-action@v2
        with:
          context: ./symfony/php/8.0/
          file: ./symfony/php/8.0/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/symfony-php:8.0
          push: ${{ github.ref == 'refs/heads/master' }}

  php_sylius_73:
    name: "Sylius - 7.3"
    runs-on: ubuntu-latest
    needs: php_symfony_73

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image (7.3 for Sylius)"
        uses: docker/build-push-action@v2
        with:
          context: ./sylius/php/7.3/
          file: ./sylius/php/7.3/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/sylius-php:7.3
          push: ${{ github.ref == 'refs/heads/master' }}

  php_sylius_74:
    name: "Sylius - 7.4"
    runs-on: ubuntu-latest
    needs: php_symfony_74

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image (7.4 for Sylius)"
        uses: docker/build-push-action@v2
        with:
          context: ./sylius/php/7.4/
          file: ./sylius/php/7.4/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: |
            ajardin/sylius-php:7.4
            ajardin/sylius-php:latest
          push: ${{ github.ref == 'refs/heads/master' }}

  php_sylius_80:
    name: "Sylius - 8.0"
    runs-on: ubuntu-latest
    needs: php_symfony_80

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image (8.0 for Sylius)"
        uses: docker/build-push-action@v2
        with:
          context: ./sylius/php/8.0/
          file: ./sylius/php/8.0/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/sylius-php:8.0
          push: ${{ github.ref == 'refs/heads/master' }}

  php_drupal_72:
    name: "Drupal - 7.2"
    runs-on: ubuntu-latest
    needs: php_symfony_72

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./drupal/php/7.2/
          file: ./drupal/php/7.2/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/drupal-php:7.2
          push: ${{ github.ref == 'refs/heads/master' }}

  php_drupal_73:
    name: "Drupal - 7.3"
    runs-on: ubuntu-latest
    needs: php_symfony_73

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./drupal/php/7.3/
          file: ./drupal/php/7.3/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: ajardin/drupal-php:7.3
          push: ${{ github.ref == 'refs/heads/master' }}

  php_drupal_74:
    name: "Drupal - 7.4"
    runs-on: ubuntu-latest
    needs: php_symfony_74

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set-up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log-in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./drupal/php/7.4/
          file: ./drupal/php/7.4/Dockerfile
          build-args: |
            BLACKFIRE_PROBE_VERSION=${{ env.BLACKFIRE_PROBE_VERSION }}
          tags: |
            ajardin/drupal-php:7.4
            ajardin/drupal-php:latest
          push: ${{ github.ref == 'refs/heads/master' }}
