name: 'Symfony - Build and Publish'

on:
  push:
    branches: ['**']
    paths: ['.github/workflows/symfony.yml', 'symfony/**']

jobs:
  nginx:
    name: 'Nginx'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/symfony-nginx
          path: symfony/nginx/
          always_pull: true
          tags: latest
          push: ${{ github.ref == 'refs/heads/master' }}

  php:
    name: 'PHP'
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare the build context'
        uses: actions/checkout@v1

      - name: 'Build & Publish the Docker image'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ajardin/symfony-php
          path: symfony/php/
          always_pull: true
          tags: latest
          push: ${{ github.ref == 'refs/heads/master' }}
